line-length = 100
target-version = "py310"

[lint]
select = ["E", "F"]
exclude = [
  ".bzr",
  ".direnv",
  ".eggs",
  ".git",
  ".hg",
  ".mypy_cache",
  ".nox",
  ".pants.d",
  ".pyenv",
  ".pytest_cache",
  ".ruff_cache",
  ".svn",
  ".tox",
  ".venv",
  "_build",
  "buck-out",
  "build",
  "dist",
  "node_modules",
  "docs",
  "mutation_results",
]
